---
version: '3'
services:
  voting-app:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 5050:80
    deploy:
      replicas: 2

  redis:
    image: redis
    ports:
      - 6380:6380

  worker-app:
    image: dockersamples/examplevotingapp_worker

  postgress-app:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: intelliqit
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb

  result-app:
    image: dockersamples/examplevotingapp_result
    ports:
      - 6060:80
    deploy:
      replicas: 2
...


