---
apiVersion: v1
kind: Pod
metadata:
  name: ghost-pod
  namespace: test-ns
  labels:
    author: intelliqit
    type: cms
spec:
  containers:
    - name: ghost-app
      image: ghost
      env:
        - name: NODE_ENV
          value: development





