---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  clusterIP: None
  ports:
    - name: tcp
      port: 3306
      protocol: TCP
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
    spec:
      containers:
        - name: mydb
          image: mysql:5
          ports:
            - containerPort: 3306
              name: tcp
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: intelliqit
          volumeMounts:
            - name: new-volume3
              mountPath: /var/lib/mysql
      volumes:
        - name: new-volume3
          persistentVolumeClaim:
            claimName: task-pv-claim3
...





    

