---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: test-ns
  labels:
    author: intelliqit
    type: proxy
    cat: rat
spec:
  containers:
    - name: mynginx
      image: nginx
...




